### ISSUE TITLE
download not finish and show error.

### ISSUE THREAD

**Issue by xueqing0622** [kijai/ComfyUI-FollowYourEmojiWrapper#1]
!!! Exception during processing!!! Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory F:\ComfyUI\ComfyUI\models\diffusers\sd-image-variations-diffusers.
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-FollowYourEmojiWrapper\nodes.py", line 93, in loadmodel
    image_encoder = CLIPVisionModelWithProjection.from_pretrained(model_path, subfolder="image_encoder").to(dtype).to(device)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 3305, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory F:\ComfyUI\ComfyUI\models\diffusers\sd-image-variations-diffusers.

**Comment by xueqing0622** [comment]
Delete the  F:\ComfyUI\ComfyUI\models\diffusers\sd-image-variations-diffusers
and redownload it works

**Comment by kijai** [comment]
Removing the folder indeed is the way to force redownload.

Also it turns out only the image_encoder from the sd-image-variations-diffusers is actually needed, so  after latest update, everything else can be deleted and in the future the node will only download that.

**Comment by xueqing0622** [comment]
Thx， kijai. It works!
